require_relative '../book'
require_relative '../Person'
require_relative '../rental'
require_relative '../Teacher'
require_relative '../Student'
require_relative '../capdecorate'
require_relative '../trimmerdecorator'
require 'yaml'
